/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface PocInterface extends ethers.utils.Interface {
  functions: {
    "testExactTokenForToken(uint256,uint256,address[])": FunctionFragment;
    "testTokenForExactToken(uint256,uint256,address[])": FunctionFragment;
    "uniswapV2Call(address,uint256,uint256,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "testExactTokenForToken",
    values: [BigNumberish, BigNumberish, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "testTokenForExactToken",
    values: [BigNumberish, BigNumberish, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapV2Call",
    values: [string, BigNumberish, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "testExactTokenForToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testTokenForExactToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapV2Call",
    data: BytesLike
  ): Result;

  events: {};
}

export class Poc extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: PocInterface;

  functions: {
    testExactTokenForToken(
      _amountIn: BigNumberish,
      _amountOutMin: BigNumberish,
      _path: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "testExactTokenForToken(uint256,uint256,address[])"(
      _amountIn: BigNumberish,
      _amountOutMin: BigNumberish,
      _path: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    testTokenForExactToken(
      _amountOut: BigNumberish,
      _amountInMax: BigNumberish,
      _path: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "testTokenForExactToken(uint256,uint256,address[])"(
      _amountOut: BigNumberish,
      _amountInMax: BigNumberish,
      _path: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    uniswapV2Call(
      _sender: string,
      _amount0: BigNumberish,
      _amount1: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "uniswapV2Call(address,uint256,uint256,bytes)"(
      _sender: string,
      _amount0: BigNumberish,
      _amount1: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  testExactTokenForToken(
    _amountIn: BigNumberish,
    _amountOutMin: BigNumberish,
    _path: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "testExactTokenForToken(uint256,uint256,address[])"(
    _amountIn: BigNumberish,
    _amountOutMin: BigNumberish,
    _path: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  testTokenForExactToken(
    _amountOut: BigNumberish,
    _amountInMax: BigNumberish,
    _path: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "testTokenForExactToken(uint256,uint256,address[])"(
    _amountOut: BigNumberish,
    _amountInMax: BigNumberish,
    _path: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  uniswapV2Call(
    _sender: string,
    _amount0: BigNumberish,
    _amount1: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "uniswapV2Call(address,uint256,uint256,bytes)"(
    _sender: string,
    _amount0: BigNumberish,
    _amount1: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    testExactTokenForToken(
      _amountIn: BigNumberish,
      _amountOutMin: BigNumberish,
      _path: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    "testExactTokenForToken(uint256,uint256,address[])"(
      _amountIn: BigNumberish,
      _amountOutMin: BigNumberish,
      _path: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    testTokenForExactToken(
      _amountOut: BigNumberish,
      _amountInMax: BigNumberish,
      _path: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    "testTokenForExactToken(uint256,uint256,address[])"(
      _amountOut: BigNumberish,
      _amountInMax: BigNumberish,
      _path: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    uniswapV2Call(
      _sender: string,
      _amount0: BigNumberish,
      _amount1: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "uniswapV2Call(address,uint256,uint256,bytes)"(
      _sender: string,
      _amount0: BigNumberish,
      _amount1: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    testExactTokenForToken(
      _amountIn: BigNumberish,
      _amountOutMin: BigNumberish,
      _path: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "testExactTokenForToken(uint256,uint256,address[])"(
      _amountIn: BigNumberish,
      _amountOutMin: BigNumberish,
      _path: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    testTokenForExactToken(
      _amountOut: BigNumberish,
      _amountInMax: BigNumberish,
      _path: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "testTokenForExactToken(uint256,uint256,address[])"(
      _amountOut: BigNumberish,
      _amountInMax: BigNumberish,
      _path: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    uniswapV2Call(
      _sender: string,
      _amount0: BigNumberish,
      _amount1: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "uniswapV2Call(address,uint256,uint256,bytes)"(
      _sender: string,
      _amount0: BigNumberish,
      _amount1: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    testExactTokenForToken(
      _amountIn: BigNumberish,
      _amountOutMin: BigNumberish,
      _path: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "testExactTokenForToken(uint256,uint256,address[])"(
      _amountIn: BigNumberish,
      _amountOutMin: BigNumberish,
      _path: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    testTokenForExactToken(
      _amountOut: BigNumberish,
      _amountInMax: BigNumberish,
      _path: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "testTokenForExactToken(uint256,uint256,address[])"(
      _amountOut: BigNumberish,
      _amountInMax: BigNumberish,
      _path: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    uniswapV2Call(
      _sender: string,
      _amount0: BigNumberish,
      _amount1: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "uniswapV2Call(address,uint256,uint256,bytes)"(
      _sender: string,
      _amount0: BigNumberish,
      _amount1: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
